version: "2"

services:
#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.8
#    ports:
#      - "2182:2182"
#    volumes:
#      - "zookeeper_data:/bitnami"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2182
      - KAFKA_CFG_ZOOKEEPER_CONNECT=192.168.110.2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper

volumes:
#  zookeeper_data:
#    driver: local
  kafka_data:
    driver: local
