version: '3.9'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    hostname: mongo
    #    restart: always
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Shanghai
    networks:
      - game
  #  TODO self build mongo and data image

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - game

  zookeeper1:
    image: zookeeper
    container_name: zookeeper1
    hostname: zookeeper1
    ports:
      - "12181:2181"
    networks:
      - game

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    links:
      - mongo:mongo
    depends_on:
      - mongo
    networks:
      - game
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 123456

  game-api1:
    image: game-api:releases
    container_name: game-api1
    hostname: game-api1
    depends_on:
      - mongo
      - zookeeper1
    links:
      - mongo:mongo
      - zookeeper1:zookeeper1
    ports:
      - "7000:7000"
    networks:
      - game

  game-gate1:
    image: game-gate:releases
    container_name: game-gate1
    hostname: game-gate1
    depends_on:
      - zookeeper1
    links:
      - zookeeper1:zookeeper1
      - game-api1:game-api1
    ports:
      - "7020:7020"
      - "7021:7021"
    networks:
      - game

  game-hall1:
    image: game-hall:releases
    container_name: game-hall1
    hostname: game-hall1
    depends_on:
      - mongo
      - zookeeper1
    links:
      - mongo:mongo
      - zookeeper1:zookeeper1
      - game-api1:game-api1
      - game-gate1:game-gate1
    ports:
      - "7030:7030"
    networks:
      - game
  game-manage1:
    image: game-manage:releases
    container_name: game-manage1
    hostname: game-manage1
    depends_on:
      - mongo
      - zookeeper1
    links:
      - mongo:mongo
      - zookeeper1:zookeeper1
      - game-api1:game-api1
      - game-gate1:game-gate1
      - game-hall1:game-hall1
    ports:
      - "7061:7061"
    networks:
      - game


networks:
  game:
    driver: bridge

